# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)
        self.video_area = QVideoWidget(Form)
        self.video_area.setGeometry(QtCore.QRect(0, 0, 671, 521))
        self.video_area.setObjectName("video_area")
        self.file_button = QtWidgets.QPushButton(Form)
        self.file_button.setGeometry(QtCore.QRect(260, 580, 91, 31))
        self.file_button.setObjectName("file_button")
        self.play_button = QtWidgets.QPushButton(Form)
        self.play_button.setGeometry(QtCore.QRect(400, 580, 91, 31))
        self.play_button.setObjectName("play_button")
        self.file_list = QtWidgets.QTextBrowser(Form)
        self.file_list.setGeometry(QtCore.QRect(670, 200, 291, 321))
        self.file_list.setObjectName("file_list")
        self.gesture_area = QVideoWidget(Form)
        self.gesture_area.setGeometry(QtCore.QRect(670, 0, 291, 201))
        self.gesture_area.setObjectName("gesture_area")
        self.video_process_slider = QtWidgets.QSlider(Form)
        self.video_process_slider.setGeometry(QtCore.QRect(10, 530, 881, 22))
        self.video_process_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_process_slider.setObjectName("video_process_slider")
        self.video_process = QtWidgets.QLabel(Form)
        self.video_process.setGeometry(QtCore.QRect(920, 530, 21, 21))
        self.video_process.setObjectName("video_process")
        self.pause_button = QtWidgets.QPushButton(Form)
        self.pause_button.setGeometry(QtCore.QRect(540, 580, 71, 31))
        self.pause_button.setObjectName("pause_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_button.setText(_translate("Form", "打开文件"))
        self.play_button.setText(_translate("Form", "播放"))
        self.file_list.setHtml(_translate("Form",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.video_process.setText(_translate("Form", "25%"))
        self.pause_button.setText(_translate("Form", "暂停"))
