# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QLabel
from ImgQLabel import ImgQLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)
        self.video_area = QVideoWidget(Form)
        self.video_area.setGeometry(QtCore.QRect(0, 20, 791, 521))
        self.video_area.setObjectName("video_area")

        self.play_button2 = ImgQLabel(Form)
        self.play_button2.setPixmap(QPixmap("D:\\HCI2022\\final\\assets\\play-button.png"))
        self.play_button2.setObjectName("play_button2")
        self.play_button2.setGeometry(QtCore.QRect(440, 590, 91, 31))
        self.play_button2.setMaximumSize(25, 25)
        self.play_button2.setScaledContents(True)

        self.previous = QtWidgets.QLabel(Form)
        self.previous.setPixmap(QPixmap("D:\\HCI2022\\final\\assets\\previous.png"))
        self.previous.setObjectName("previous")
        self.previous.setGeometry(QtCore.QRect(300, 590, 71, 41))
        self.previous.setMaximumSize(25, 25)
        self.previous.setScaledContents(True)

        self.next = QtWidgets.QLabel(Form)
        self.next.setPixmap(QPixmap("D:\\HCI2022\\final\\assets\\next.png"))
        self.next.setObjectName("next")
        self.next.setGeometry(QtCore.QRect(580, 590, 71, 41))
        self.next.setMaximumSize(25, 25)
        self.next.setScaledContents(True)

        self.video_area.setGeometry(QtCore.QRect(0, 20, 791, 521))
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 23))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.score = QtWidgets.QMenu(self.menubar)
        self.score.setObjectName("score")
        self.video_process_slider = QtWidgets.QSlider(Form)
        self.video_process_slider.setGeometry(QtCore.QRect(70, 560, 801, 22))
        self.video_process_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_process_slider.setObjectName("video_process_slider")
        self.video_process = QtWidgets.QLabel(Form)
        self.video_process.setGeometry(QtCore.QRect(880, 560, 41, 21))
        self.video_process.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.video_process.setObjectName("video_process")
        self.video_list = QtWidgets.QLabel(Form)
        self.video_list.setGeometry(QtCore.QRect(1280, 960, 171, 491))
        self.video_list.setObjectName("video_list")

        self.player_volume = QtWidgets.QSlider(Form)
        self.player_volume.setGeometry(QtCore.QRect(730, 590, 111, 16))
        self.player_volume.setOrientation(QtCore.Qt.Horizontal)
        self.player_volume.setObjectName("player_volume")
        self.fileOpenAction = QtWidgets.QAction(Form)
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileNewAction = QtWidgets.QAction(Form)
        self.fileNewAction.setObjectName("fileNewAction")
        self.fileCloseAction = QtWidgets.QAction(Form)
        self.fileCloseAction.setObjectName("fileCloseAction")
        self.file.addAction(self.fileOpenAction)
        self.file.addAction(self.fileNewAction)
        self.file.addAction(self.fileCloseAction)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.score.menuAction())
        Form.setMenuBar(self.menubar)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.video_process.setText(_translate("Form", "25%"))
        self.video_list.setText(_translate("Form", "test"))
        self.file.setTitle(_translate("Form", "文件"))
        self.score.setTitle(_translate("Form", "评价"))
        self.fileOpenAction.setText(_translate("MainWindow", "打开"))
        self.fileOpenAction.setShortcut(_translate("MainWindow", "Alt+O"))
        self.fileNewAction.setText(_translate("MainWindow", "新建"))
        self.fileNewAction.setShortcut(_translate("MainWindow", "Alt+N"))
        self.fileCloseAction.setText(_translate("MainWindow", "关闭"))
        self.fileCloseAction.setShortcut(_translate("MainWindow", "Alt+C"))
