# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)
        self.video_area = QVideoWidget(Form)
        self.video_area.setGeometry(QtCore.QRect(0, 0, 791, 521))
        self.video_area.setObjectName("video_area")
        self.file_button = QtWidgets.QPushButton(Form)
        self.file_button.setGeometry(QtCore.QRect(260, 580, 91, 31))
        self.file_button.setObjectName("file_button")
        self.play_button = QtWidgets.QPushButton(Form)
        self.play_button.setGeometry(QtCore.QRect(440, 580, 91, 31))
        self.play_button.setObjectName("play_button")
        self.video_process_slider = QtWidgets.QSlider(Form)
        self.video_process_slider.setGeometry(QtCore.QRect(60, 530, 801, 22))
        self.video_process_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_process_slider.setObjectName("video_process_slider")
        self.video_process = QtWidgets.QLabel(Form)
        self.video_process.setGeometry(QtCore.QRect(900, 530, 21, 21))
        self.video_process.setObjectName("video_process")
        self.pause_button = QtWidgets.QPushButton(Form)
        self.pause_button.setGeometry(QtCore.QRect(620, 580, 71, 31))
        self.pause_button.setObjectName("pause_button")
        self.video_list = QtWidgets.QLabel(Form)
        self.video_list.setGeometry(QtCore.QRect(790, 30, 171, 491))
        self.video_list.setObjectName("video_list")
        self.video_list_name = QtWidgets.QLabel(Form)
        self.video_list_name.setGeometry(QtCore.QRect(790, 0, 171, 31))
        self.video_list_name.setAlignment(QtCore.Qt.AlignCenter)
        self.video_list_name.setObjectName("video_list_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_button.setText(_translate("Form", "打开文件"))
        self.play_button.setText(_translate("Form", "播放"))
        self.video_process.setText(_translate("Form", "25%"))
        self.pause_button.setText(_translate("Form", "暂停"))
        self.video_list.setText(_translate("Form", "test"))
        self.video_list_name.setText(_translate("Form", "播放列表"))
